service: liist-auth

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  auth:
    handler: handler.auth
    events:
      - http: GET token
    memorySize: 128
    timeout: 10

plugins:
  - serverless-plugin-include-dependencies
